### ISSUE TITLE
Sort _id in descending order by default

### ISSUE THREAD

**Issue by boblauer** [jeromelebel/MongoHub-Mac#129]
Maybe I'm the only one, but I would always prefer to see the most recent records created first.  I almost always have to override the default _id sort to be descending instead of ascending.

I'd be interested to see if this is an issue for others as well.  Very rarely have I ever wanted to sort _id in ascending order.

**Comment by jeromelebel** [comment]
Should be fixed in 3.1. I let you verify this issue and close it.

**Comment by boblauer** [comment]
Fantastic.  Thank you much!
