### ISSUE TITLE
No collections listed

### ISSUE THREAD

**Issue by respectTheCode** [jeromelebel/MongoHub-Mac#14]
When connecting to a db over ssh no collections are listed. The server status does show up and work though.

**Comment by finscn** [comment]
This bug is reborn .

No collection list  at localhost db,  it's ok for remote db (via ssh) 
Mac OS X is 10.10

**Comment by starplanet** [comment]
+1. No collection list at localhost.

my versions is:
Mac OSX is 10.11.4
mongohub: 2.3.2[73]

**Comment by SamDecrock** [comment]
+1. Only "test" collection is shown

Mac OSX: 10.11.6 (El Capitan)
Mongohub: 2.3.2[73]

**Comment by SamDecrock** [comment]
Ok, I just download 3.1.4 off this github page and it works. Sorry for the troubles.
