### ISSUE TITLE
Make keyboard shortcut to delete records optional

### ISSUE THREAD

**Issue by boblauer** [jeromelebel/MongoHub-Mac#144]
I'm very used to using cmd + delete to delete an entire line of text.  Having this be the keyboard shortcut to delete a record has caused me to accidentally delete several records.  I would recommend either requiring confirmation when using the keyboard shortcut, or using a different key combination, or being able to disable the key combination altogether.

**Comment by jenskdsgn** [comment]
It is good to see that this happened to other as well! Record deletion should absolutely require confirmation!!!
