### ISSUE TITLE
MySQL import not working

### ISSUE THREAD

**Issue by morenoh149** [jeromelebel/MongoHub-Mac#181]
So after finding out how to add the `import(MySQL)` button I tried to perform an import. I'm running my mysql on my local machine and am confident the credentials are right because mongohub lists the right database names in the dropdown after clicking `connect`.

What needs to go into `Collection` under `Import to MongoDB Collection`? I can choose from several tables. Can modify the chunk size. But no matter what I put into the `Collection` field nothing happens after clicking `Import`. Any help here?
![screenshot 2014-12-16 21 12 02](https://cloud.githubusercontent.com/assets/587438/5466812/364fbd20-8568-11e4-9c91-d5854374230e.png)

**Comment by jeromelebel** [comment]
I need help to get a mysql server working... I tried with macports, but there is no network by default. I don't know how to activate the network.

**Comment by jeromelebel** [comment]
I finally got mysql server working. But I was able to import 10000 documents from mysql. I need help to understand how to reproduce the bug.

**Comment by morenoh149** [comment]
@jeromelebel that's great! I no longer have the mysql db though :( maybe @tvdsluijs has his.

**Comment by silentwarrior** [comment]
I have the same problem.

I choose my remote database, connect perfectly. Lists tables in the database I choose, select one, and when I press Import it does nothing, regardless if the Collection input box has an existing collection name or a non existing one. Its like the button click isnt tied to anything.

**Comment by jeromelebel** [comment]
This error should have been fixed in 3.1b1

**Comment by morenoh149** [comment]
@silentwarrior please try the latest beta version and let us know if the issue has been fixed so we can close this issue.

**Comment by silentwarrior** [comment]
Hello.

Re-downloaded the binary from this page, tried it again, same problem.

**Comment by jeromelebel** [comment]
Did you ask for the beta version in the preferences of MongoHub?

**Comment by silentwarrior** [comment]
I didn’t.

Added, and tried it out, worked perfectly.

Thank you.

On Mon, Feb 2, 2015 at 9:01 PM, Jérôme Lebel <notifications@github.com>
wrote:

> Did you ask for the beta version in the preferences of MongoHub?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeromelebel/MongoHub-Mac/issues/181#issuecomment-72536927>
> .
>



-- 
Regards
SilentWarrior
