### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by calfzhou** [jeromelebel/MongoHub-Mac#187]
v3.0.8, i downloaded the release zip, open the project via XCode, and then click `build`, got one error:

/path/to/MongoHub-Mac-3.0.8/Sources/Exporter-Importer/MHMysqlExportWindowController.m:91:57: Incompatible block pointer types sending 'BOOL (^)(uint64_t, MODSortedMutableDictionary *)' to parameter of type 'BOOL (^)(uint64_t, MODSortedDictionary *)'

**Comment by calfzhou** [comment]
i'm using mac os 10.10.1, xcode 6.1

**Comment by jeromelebel** [comment]
I don't see MODSortedMutableDictionary in line 91: https://github.com/jeromelebel/MongoHub-Mac/blob/master/Sources/Exporter-Importer/MHMysqlExportWindowController.m#L91

**Comment by calfzhou** [comment]
@jeromelebel i'm using release 3.0.8: https://github.com/jeromelebel/MongoHub-Mac/blob/3.0.8/Sources/Exporter-Importer/MHMysqlExportWindowController.m#L91

**Comment by jeromelebel** [comment]
Ah, I understand, you have the 3.0.8 MongoHub source with the latest version of the Mongo-Objc-Driver. It would be better to get the source with git, or to download the latest version if MongoHub

**Comment by calfzhou** [comment]
Thanks. Now another issue with latest code: /Users/zhouji/tools/MongoHub-Mac/Sources/MHPreferenceWindowController.m:213:9: 'NSBeginAlertSheet' is deprecated: first deprecated in OS X 10.10 - Use NSAlert instead

**Comment by jeromelebel** [comment]
Well, I'm supporting 10.8 and 10.9 too. So this can't be fixed yet (and that's why I don't see a warning on my side).

**Comment by calfzhou** [comment]
I changed build target to 10.8 or 10.9, a new error is `path/to/MongoHub-Mac/Sources/Exporter-Importer/MHImportExportFeedback.m:16:19: 'loadNibNamed:owner:' is deprecated: first deprecated in OS X 10.8`

Now i successfully build for 10.7. Thanks!

**Comment by jeromelebel** [comment]
Does it work for you? If so can you close the issue?

**Comment by calfzhou** [comment]
Ok for me.
