### ISSUE TITLE
Can't build :(

### ISSUE THREAD

**Issue by demands** [jeromelebel/MongoHub-Mac#190]
I just tried to build MongoHub in Xcode, both from the `master` branch and from release `3.0.8`, and I see the following error message:

```
/Users/me/Projects/MongoHub-Mac/Sources/MHPreferenceWindowController.h:9:9: 'MongoObjCDriver/MongoObjCDriver.h' file not found
```

Do I need to install dependencies from somewhere before I can build? Is there something else I'm missing?

I'm not super familiar with XCode or ObjectiveC, so please forgive me if this error report isn't particularly helpful. (And let me know how I can help diagnose!)

**Comment by jeromelebel** [comment]
How did you get the sources?

**Comment by demands** [comment]
I tried two ways:

- `git clone thisrepo`
- Downloading the latest release on the releases page

**Comment by jeromelebel** [comment]
if you do : git clone git@github.com:jeromelebel/MongoHub-Mac.git I don't see any reason why you should have a problem while doing a build with Xcode.

**Comment by calfzhou** [comment]
I met this error days before. I fixed it by manually update the submodule in Libraries/MongoObjCDriver

**Comment by jeromelebel** [comment]
you should not have this error with git clone. There is a script in Xcode to get MongoObjCDriver automatically.

**Comment by calfzhou** [comment]
on my side, the script failed with error `Needed a single revision` when executing `git submodule update --init`.

**Comment by demands** [comment]
Thanks for your help! I tried again this morning and it worked. I think my connection to github was being flakey; the submodule download must have failed.
