### ISSUE TITLE
App close on replica set connection

### ISSUE THREAD

**Issue by pcorderoe** [jeromelebel/MongoHub-Mac#196]
Hi, 
when i try to connect using a replica set option the program close. I have a cluster over Google Cloud. I'll try to connect using this mongodb://xxx.xxx.xxx.xxx:27017,xx.xx.xx.xx:27017 but don't work. Please help!

**Comment by jeromelebel** [comment]
Which version do you use? Do you mean there is a crash? Can you give me the full details of the crash?

**Comment by tdegrunt** [comment]
I'm able to connect to a replicaset, using the following for the servers field:

```
db1.ams2.do.dev:27017,db2.ams2.do.dev:27017,db3.ams2.do.dev:27017
```

If you enter it exactly like this, does it still crash?
Also have you filled in a "Set Name"?

If it still doesn't work, can you show a screenshot of the settings?

**Comment by pcorderoe** [comment]
Thanks for your answers.  I fill form like this:

Name:Replica Set
Set Name: rs0
Servers: mongodb://xxx.xxx.xxx.xxx:27017,xxx.xxx.xx.x:27017
ReadMode: Primary Preferred


[errormongohub.pdf | uploaded via ZenHub](https://files.zenhub.io/54dcd13356e8c9c658df427f)

**Comment by tdegrunt** [comment]
Can you drop the mongodb://  and try again?

**Comment by jeromelebel** [comment]
Yes, that should be the reason of the crash. I need to fix this issue.

**Comment by pcorderoe** [comment]
i try (without mongodb://) but show an error message: No aceptable peer could be found

**Comment by jeromelebel** [comment]
do you use ssh tunneling?

**Comment by tdegrunt** [comment]
Can you connect to each of the servers from the command line using the following?
```
mongo --host xxx.xxx.xxx.xxx:27017
```

If not, what are you using? Also the output of `rs.status()` on the mongo console might help debug this.

**Comment by pcorderoe** [comment]
i am using normal connection, with Server: Standalone, one connection for each server, and work fine

**Comment by pcorderoe** [comment]
I'm not using ssh tunneling

**Comment by jeromelebel** [comment]
Should be fixed in 3.1. I let you verify this issue and close it.

**Comment by bolerovt** [comment]
same problem here, can not connect replica set, but can connect to each stand alone server

**Comment by bolerovt** [comment]
do we need to wait until the mongo 3.1 to fix this issue?
