### ISSUE TITLE
Crash when using Authentication on Mongo 3

### ISSUE THREAD

**Issue by dustinblackman** [jeromelebel/MongoHub-Mac#200]
When attempting to connect to a Mongo 3 RC9 instance with Auth enabled, MongoHub 3.1 beta 3 will crash.

**Comment by jeromelebel** [comment]
Could you give the full crash report?
Thanks

**Comment by dustinblackman** [comment]
Never debugged Mac applications before, hopefully this is what you're wanting! 

https://gist.github.com/dustinblackman/034663e58ded449b3c58

**Comment by jeromelebel** [comment]
Perfect!

**Comment by dustinblackman** [comment]
Appreciate the super fast commit, thanks! :D
Though, I just kill my local repo, repulled, and built, and still get a crash on auth. :(
https://gist.github.com/dustinblackman/dad49772572af1b65313

**Comment by jeromelebel** [comment]
Try again to get the latest version. It might be better now.

**Comment by dustinblackman** [comment]
No crash anymore! Though another error instead. I could be my Mongo instance, but I have other drivers (Python and Node) connecting just fine. 

![image](https://cloud.githubusercontent.com/assets/5246169/6336774/1711a7f2-bb73-11e4-9c8c-e5fbd5e3be56.png)

**Comment by lelandcope** [comment]
Im actually still getting the crash on release 3.1b3. Its the same exact error as the gist above.

**Comment by dustinblackman** [comment]
If you build from the last commit, the crash error goes away but you get the SCRAM failure like in the screenshot above.

**Comment by ppdg** [comment]
Same issue with Mongo 3

**Comment by jeromelebel** [comment]
I've merged the latest version of mongo c driver in mongohub. I'm not able to test it right now, but maybe the issue has been fixed. If someone has 5mn to try that would be great.

**Comment by jeromelebel** [comment]
Should be fixed in 3.1b4

**Comment by ppdg** [comment]
Thx you for this reactivity,
I have downloaded last version, 3.1b4, There is no crash now :). 

But always an error,
- After ssh conexion on my server : mongo --port 27017 -u user -p pwd --authenticationDatabase test
No problem,

- Same configuration on mongohub : 
![capture d ecran 2015-03-06 a 15 27 34](https://cloud.githubusercontent.com/assets/6069599/6526833/189e5e84-c416-11e4-863b-ffafc20ef2d9.png)

I did not find how to display the text, sorry, i can't increase the column. 


PS : no problem on other servers with mongo2

**Comment by jeromelebel** [comment]
can you explain me how you added the password to mongodb?

**Comment by jeromelebel** [comment]
Did you put "test" in the connection panel?

**Comment by dustinblackman** [comment]
I get the name error, and this is likely an issue with the driver. I had the same problem with the Python and PHP driver stating that it couldn't auth, until I did an upgrade and then everything was normal.

**Comment by lelandcope** [comment]
Im also getting the same error above on the latest version. My user name and passwords were setup using Mongodb MMS system. I hope that helps.

**Comment by ppdg** [comment]
Yep, something like this, 

use test
db.createUser(
  {
    user: "user",
    pwd: "pwd",
    roles: [ { role: "userAdmin", db: "test" } ]
  }
)

![capture d ecran 2015-03-06 a 20 42 07](https://cloud.githubusercontent.com/assets/6069599/6534919/48dee5f2-c441-11e4-8ce3-eb47c0777b2f.png)


i will try quickly with no auth for tcheck.

**Comment by jeromelebel** [comment]
I don't have any issue with that test. Of course it doesn't work if I don't specify the database name, but with, it works.

**Comment by dustinblackman** [comment]
Ah, seems I've found the issue. All good on my end. My mistake!

**Comment by ppdg** [comment]
Ok, thanks for all :+1: , i will test with a clean install tonight :)

**Comment by ppdg** [comment]
Ok it's good with a clean install :+1: Thanks for all :)
