### ISSUE TITLE
Can't create database in mongoHub

### ISSUE THREAD

**Issue by zhaozhiming** [jeromelebel/MongoHub-Mac#203]
HI ALL,
I'm a newer to mongodb, I use docker mongo image to run mongodb (https://registry.hub.docker.com/_/mongo/), and I can connect to the mongodb server, but I can't create database in the mongoHub.
After I input the db name, it can't show any databases, Anyone hep? Thanks.

![screen shot 2015-02-26 at 11 03 43 am](https://cloud.githubusercontent.com/assets/1436694/6385637/7f7dee78-bda7-11e4-988e-90a0f9a82024.png)
![screen shot 2015-02-26 at 11 04 07 am](https://cloud.githubusercontent.com/assets/1436694/6385639/88e9ee62-bda7-11e4-8cc3-a9ef5cc1a54c.png)
![screen shot 2015-02-26 at 11 04 28 am](https://cloud.githubusercontent.com/assets/1436694/6385640/89193aaa-bda7-11e4-946e-ca62f24dfb59.png)

**Comment by jeromelebel** [comment]
Which version of mongohub?
which version of mongodb?

**Comment by zhaozhiming** [comment]
mongodb version: 3.0.0-rc8
mongohub version: 3.0.8

**Comment by zhaozhiming** [comment]
so this is a bug and it'll be fixed in the next version?

**Comment by jeromelebel** [comment]
Mongodb 3.0 doesn't behave exactly the same way than before. And MongoHub was not doing the right thing to create a database. It was ok before. But this doesn't work anymore with mongodb 3.0.

I've fixed it. This fix will appear in the next version of mongohub beta (3.1b4).

**Comment by zhaozhiming** [comment]
ok, thanks.

**Comment by ghost** [comment]
Still have this issue.
MongoDB: 3.0.6
MongoHub: 3.1.5b1

**Comment by ashtonian** [comment]
still have this issues. 

MongoDb: 3.0.7
MongoHub: 3.1.4
