### ISSUE TITLE
Viewing document with `Infinity` value throws error

### ISSUE THREAD

**Issue by creynders** [jeromelebel/MongoHub-Mac#206]
If you have a double float field in your schema with a value of `Number.INFINITY` mongohub throws an error when you try to view the json.

Example: (`scale` is the field we're interested in here)

Double clicking on this:
![screen shot 2015-03-04 at 16 58 04](https://cloud.githubusercontent.com/assets/436347/6487233/4270b7b6-c290-11e4-81b1-b689ca756c55.png)

creates this:

![screen shot 2015-03-04 at 16 58 18](https://cloud.githubusercontent.com/assets/436347/6487245/4fa9f532-c290-11e4-8eee-f6ae974faaf2.png)

When I change the value to anything else numerically valid the error disappears. Haven't tried it with negative infinity yet, but I assume the same occurs.

**Comment by creynders** [comment]
This is with Mongohub 3.0.7 BTW

**Comment by jeromelebel** [comment]
Should be fixed in 3.1b4

**Comment by creynders** [comment]
Cool, that's fast! :beers:

**Comment by jeromelebel** [comment]
You are welcome! You can close the issue if it works for you.

**Comment by creynders** [comment]
Need to compile from source I assume? Or is there a beta binary download?

**Comment by jeromelebel** [comment]
You can get the beta from the Mongohub preferences.

**Comment by jeromelebel** [comment]
Should be fixed in 3.1. I let you verify this issue and close it.

**Comment by creynders** [comment]
Hi there, yeah, clicking "Check for updates" did/does nothing, with a ticked or unticked "Download beta versions" changing nothing. I'll D/L the latest version manually and verify this Infinity issue.

**Comment by creynders** [comment]
Ok, 3.1.3 does work with `Infinity` now. (Update troubles have disappeared too)
