### ISSUE TITLE
Databases not expanding on mongodb 3.0.1 with wiredTiger

### ISSUE THREAD

**Issue by marcinrosinski** [jeromelebel/MongoHub-Mac#214]
Hi, I have just upgraded our servers to the latest mongo 3.0.1 using wiredTiger storage engine and can't expand any database to see collection although they are in there as can see all OK when using mongo client.

My MongoHub version = 3.0.8

**Comment by jeromelebel** [comment]
Should be fixed in 3.1. I let you verify this issue and close it.

**Comment by marcinrosinski** [comment]
Thanks @jeromelebel, all works good now.
