### ISSUE TITLE
Add a COPYING file with the license text and/or a statement about the license in README

### ISSUE THREAD

**Issue by krichter722** [jeromelebel/MongoHub-Mac#217]

**Comment by jeromelebel** [comment]
Sorry, I can't do that, I don't own all the code.

**Comment by jeromelebel** [comment]
For my code, do what ever you want with it.

**Comment by krichter722** [comment]
OK, understood. It'd still be helpful to write exactly that into a `COPYING` because it's the first address to get an overview on licensing - it doesn't have to be a copy-paste of the known license texts afaik.

**Comment by jeromelebel** [comment]
By the way, there is already a copyright in https://github.com/jeromelebel/MongoHub-Mac/blob/master/Resources/MongoHub-Info.plist related to The Peppers Studio
