### ISSUE TITLE
Sort fields in output?

### ISSUE THREAD

**Issue by computron** [jeromelebel/MongoHub-Mac#77]
Is there a way to see the returned document with the keys (fields) sorted alphabetically? I have many fields in my output document and it would be easier to browse if I could have alphabetical sort.

**Comment by jeromelebel** [comment]
Should be fixed in 3.1. I let you verify this issue and close it.

**Comment by computron** [comment]
I just installed 3.1.4 but could not see the sorted keys. It's possible I need to click something and missed it. Here's a screenshot of what I see; what I would like to see are the keys sorted alphabetically, e.g. "battid" before "max_delta_volume".

![2015-03-30 01 03 00 pm](https://cloud.githubusercontent.com/assets/986759/6905489/318ca660-d6dd-11e4-8ab3-28916825a382.png)

**Comment by jeromelebel** [comment]
You can change that in the application preference

**Comment by computron** [comment]
works, thanks!
