### ISSUE TITLE
Filtering on date

### ISSUE THREAD

**Issue by wichert** [jeromelebel/MongoHub-Mac#94]
I am trying to filter on a basic date field. Normally I can do something like this:

```
> db.transaction.find({"timestamp": {"$gte": new ISODate("2013-10-04")}})
```

Trying to use the same filter in MongoHub results in a syntax error: `unexpected char in the current parser context - "{"$gte": new ISODate"`

**Comment by jgallen23** [comment]
looks like #25 was fixed, but this is still not working for me.  Should we reopen this one?

**Comment by dorongutman** [comment]
not working for me as well (isodate or whatever)

**Comment by nobusue** [comment]
still not resolved?

**Comment by arm77** [comment]
Filtering based on Unix epoch works (e.g. {timestamp: {"$gte": new Date(1507420800000)} }

Using MongoHub 3.1.4
